drop table REGIONTest cascade constraint purge;
drop table NATIONTest cascade constraint purge;
drop table CUSTOMERTest cascade constraint purge;

CREATE TABLE REGIONTest(
R_REGIONKEY	NUMBER(12)	NOT NULL,
R_NAME		CHAR(25)	NOT NULL,
R_COMMENT	VARCHAR(152)	NOT NULL,
	CONSTRAINT REGIONTest_PKEY PRIMARY KEY(R_REGIONKEY),
	CONSTRAINT REGIONTest_CHECK1 CHECK(R_REGIONKEY >= 0) );

CREATE TABLE NATIONTest(
N_NATIONKEY	NUMBER(12)	NOT NULL,
N_NAME		CHAR(25)	NOT NULL,
N_REGIONKEY	NUMBER(12)	NOT NULL,
N_COMMENT	VARCHAR(152)	NOT NULL,
	CONSTRAINT NATIONTest_PKEY PRIMARY KEY (N_NATIONKEY),
	CONSTRAINT NATIONTest_FKEY1 FOREIGN KEY (N_REGIONKEY)
		REFERENCES REGIONTest(R_REGIONKEY),
	CONSTRAINT NATIONTest_CHECK1 CHECK(N_NATIONKEY >= 0) );

CREATE TABLE CUSTOMERTest(
C_CUSTKEY	NUMBER(12)	NOT NULL,
C_NAME 		VARCHAR(25)	NOT NULL,
C_ADDRESS	VARCHAR(40)	NOT NULL,
C_NATIONKEY	NUMBER(12)	NOT NULL,
C_PHONE		CHAR(15)	NOT NULL,
C_ACCTBAL	NUMBER(12,2)	NOT NULL,
C_MKTSEGMENT	CHAR(10)	NOT NULL,
C_COMMENT	VARCHAR(117)	NOT NULL,
	CONSTRAINT CUSTOMERTest_PKEY PRIMARY KEY(C_CUSTKEY),
	CONSTRAINT CUSTOMERTest_FKEY1 FOREIGN kEY (C_NATIONKEY)
		REFERENCES NATIONTest(N_NATIONKEY),
	CONSTRAINT CUSTOMERTest_CHECK1 CHECK(C_CUSTKEY >= 0) );
